/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChildProfile {
  'name' : string,
  'childId' : bigint,
  'colorTag' : string,
  'balanceCents' : bigint,
}
export interface Chore {
  'name' : string,
  'rewardCents' : bigint,
  'frequency' : Frequency,
  'assignedChildIds' : Array<bigint>,
  'choreId' : bigint,
}
export interface ChoreCompletion {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'completionId' : bigint,
  'childId' : bigint,
  'timestamp' : bigint,
  'choreId' : bigint,
}
export type Frequency = { 'unlimitedDaily' : null } |
  { 'oncePerWeek' : null } |
  { 'oncePerDay' : null };
export interface Transaction {
  'transactionType' : TransactionType,
  'note' : [] | [string],
  'amountCents' : bigint,
  'childId' : bigint,
  'timestamp' : bigint,
  'choreId' : [] | [bigint],
  'transactionId' : bigint,
}
export type TransactionType = { 'deduction' : null } |
  { 'choreComplete' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'linkedChildId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyDeduction' : ActorMethod<[bigint, bigint, string], bigint>,
  'approveCompletion' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeChore' : ActorMethod<[bigint, bigint], bigint>,
  'createChild' : ActorMethod<[string, string], bigint>,
  'createChore' : ActorMethod<
    [string, bigint, Frequency, Array<bigint>],
    bigint
  >,
  'deleteChild' : ActorMethod<[bigint], undefined>,
  'deleteChore' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChild' : ActorMethod<[bigint], [] | [ChildProfile]>,
  'getChildBalance' : ActorMethod<[bigint], bigint>,
  'getChildTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getChore' : ActorMethod<[bigint], [] | [Chore]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChildren' : ActorMethod<[], Array<ChildProfile>>,
  'listChores' : ActorMethod<[], Array<Chore>>,
  'listPendingCompletions' : ActorMethod<[], Array<ChoreCompletion>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setParentPin' : ActorMethod<[string], undefined>,
  'updateChild' : ActorMethod<[bigint, string, string], undefined>,
  'updateChore' : ActorMethod<
    [bigint, string, bigint, Frequency, Array<bigint>],
    undefined
  >,
  'verifyParentPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];