/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Frequency = IDL.Variant({
  'unlimitedDaily' : IDL.Null,
  'oncePerWeek' : IDL.Null,
  'oncePerDay' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'linkedChildId' : IDL.Opt(IDL.Nat),
});
export const ChildProfile = IDL.Record({
  'name' : IDL.Text,
  'childId' : IDL.Nat,
  'colorTag' : IDL.Text,
  'balanceCents' : IDL.Int,
});
export const TransactionType = IDL.Variant({
  'deduction' : IDL.Null,
  'choreComplete' : IDL.Null,
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'note' : IDL.Opt(IDL.Text),
  'amountCents' : IDL.Int,
  'childId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'choreId' : IDL.Opt(IDL.Nat),
  'transactionId' : IDL.Nat,
});
export const Chore = IDL.Record({
  'name' : IDL.Text,
  'rewardCents' : IDL.Nat,
  'frequency' : Frequency,
  'assignedChildIds' : IDL.Vec(IDL.Nat),
  'choreId' : IDL.Nat,
});
export const ChoreCompletion = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'completionId' : IDL.Nat,
  'childId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'choreId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyDeduction' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Nat], []),
  'approveCompletion' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeChore' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createChild' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createChore' : IDL.Func(
      [IDL.Text, IDL.Nat, Frequency, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteChild' : IDL.Func([IDL.Nat], [], []),
  'deleteChore' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChild' : IDL.Func([IDL.Nat], [IDL.Opt(ChildProfile)], ['query']),
  'getChildBalance' : IDL.Func([IDL.Nat], [IDL.Int], ['query']),
  'getChildTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getChore' : IDL.Func([IDL.Nat], [IDL.Opt(Chore)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChildren' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
  'listChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
  'listPendingCompletions' : IDL.Func(
      [],
      [IDL.Vec(ChoreCompletion)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setParentPin' : IDL.Func([IDL.Text], [], []),
  'updateChild' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateChore' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, Frequency, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'verifyParentPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Frequency = IDL.Variant({
    'unlimitedDaily' : IDL.Null,
    'oncePerWeek' : IDL.Null,
    'oncePerDay' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'linkedChildId' : IDL.Opt(IDL.Nat),
  });
  const ChildProfile = IDL.Record({
    'name' : IDL.Text,
    'childId' : IDL.Nat,
    'colorTag' : IDL.Text,
    'balanceCents' : IDL.Int,
  });
  const TransactionType = IDL.Variant({
    'deduction' : IDL.Null,
    'choreComplete' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'note' : IDL.Opt(IDL.Text),
    'amountCents' : IDL.Int,
    'childId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'choreId' : IDL.Opt(IDL.Nat),
    'transactionId' : IDL.Nat,
  });
  const Chore = IDL.Record({
    'name' : IDL.Text,
    'rewardCents' : IDL.Nat,
    'frequency' : Frequency,
    'assignedChildIds' : IDL.Vec(IDL.Nat),
    'choreId' : IDL.Nat,
  });
  const ChoreCompletion = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'completionId' : IDL.Nat,
    'childId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'choreId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyDeduction' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Nat], []),
    'approveCompletion' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeChore' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createChild' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createChore' : IDL.Func(
        [IDL.Text, IDL.Nat, Frequency, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteChild' : IDL.Func([IDL.Nat], [], []),
    'deleteChore' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChild' : IDL.Func([IDL.Nat], [IDL.Opt(ChildProfile)], ['query']),
    'getChildBalance' : IDL.Func([IDL.Nat], [IDL.Int], ['query']),
    'getChildTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getChore' : IDL.Func([IDL.Nat], [IDL.Opt(Chore)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChildren' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
    'listChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
    'listPendingCompletions' : IDL.Func(
        [],
        [IDL.Vec(ChoreCompletion)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setParentPin' : IDL.Func([IDL.Text], [], []),
    'updateChild' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateChore' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, Frequency, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'verifyParentPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };