/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    transactionType: TransactionType;
    note?: string;
    amountCents: bigint;
    childId: bigint;
    timestamp: bigint;
    choreId?: bigint;
    transactionId: bigint;
}
export interface ChildProfile {
    name: string;
    childId: bigint;
    colorTag: string;
    balanceCents: bigint;
}
export interface ChoreCompletion {
    status: Variant_pending_approved_rejected;
    completionId: bigint;
    childId: bigint;
    timestamp: bigint;
    choreId: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    linkedChildId?: bigint;
}
export interface Chore {
    name: string;
    rewardCents: bigint;
    frequency: Frequency;
    assignedChildIds: Array<bigint>;
    choreId: bigint;
}
export enum Frequency {
    unlimitedDaily = "unlimitedDaily",
    oncePerWeek = "oncePerWeek",
    oncePerDay = "oncePerDay"
}
export enum TransactionType {
    deduction = "deduction",
    choreComplete = "choreComplete"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyDeduction(childId: bigint, amountCents: bigint, note: string): Promise<bigint>;
    approveCompletion(completionId: bigint, approve: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeChore(childId: bigint, choreId: bigint): Promise<bigint>;
    createChild(name: string, colorTag: string): Promise<bigint>;
    createChore(name: string, rewardCents: bigint, frequency: Frequency, assignedChildIds: Array<bigint>): Promise<bigint>;
    deleteChild(childId: bigint): Promise<void>;
    deleteChore(choreId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChild(childId: bigint): Promise<ChildProfile | null>;
    getChildBalance(childId: bigint): Promise<bigint>;
    getChildTransactions(childId: bigint): Promise<Array<Transaction>>;
    getChore(choreId: bigint): Promise<Chore | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listChildren(): Promise<Array<ChildProfile>>;
    listChores(): Promise<Array<Chore>>;
    listPendingCompletions(): Promise<Array<ChoreCompletion>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setParentPin(pin: string): Promise<void>;
    updateChild(childId: bigint, name: string, colorTag: string): Promise<void>;
    updateChore(choreId: bigint, name: string, rewardCents: bigint, frequency: Frequency, assignedChildIds: Array<bigint>): Promise<void>;
    verifyParentPin(pin: string): Promise<boolean>;
}
import type { ChildProfile as _ChildProfile, Chore as _Chore, ChoreCompletion as _ChoreCompletion, Frequency as _Frequency, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyDeduction(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyDeduction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyDeduction(arg0, arg1, arg2);
            return result;
        }
    }
    async approveCompletion(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCompletion(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeChore(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.completeChore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeChore(arg0, arg1);
            return result;
        }
    }
    async createChild(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChild(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChild(arg0, arg1);
            return result;
        }
    }
    async createChore(arg0: string, arg1: bigint, arg2: Frequency, arg3: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChore(arg0, arg1, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChore(arg0, arg1, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteChild(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChild(arg0);
            return result;
        }
    }
    async deleteChore(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChore(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChild(arg0: bigint): Promise<ChildProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChild(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChild(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildBalance(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildBalance(arg0);
            return result;
        }
    }
    async getChildTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildTransactions(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildTransactions(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChore(arg0: bigint): Promise<Chore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChore(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChore(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChildren(): Promise<Array<ChildProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChildren();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChildren();
            return result;
        }
    }
    async listChores(): Promise<Array<Chore>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChores();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChores();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingCompletions(): Promise<Array<ChoreCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingCompletions();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingCompletions();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setParentPin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setParentPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setParentPin(arg0);
            return result;
        }
    }
    async updateChild(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChild(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChild(arg0, arg1, arg2);
            return result;
        }
    }
    async updateChore(arg0: bigint, arg1: string, arg2: bigint, arg3: Frequency, arg4: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChore(arg0, arg1, arg2, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChore(arg0, arg1, arg2, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async verifyParentPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyParentPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyParentPin(arg0);
            return result;
        }
    }
}
function from_candid_ChoreCompletion_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChoreCompletion): ChoreCompletion {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Chore_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chore): Chore {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Frequency_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frequency): Frequency {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChildProfile]): ChildProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chore]): Chore | null {
    return value.length === 0 ? null : from_candid_Chore_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    note: [] | [string];
    amountCents: bigint;
    childId: bigint;
    timestamp: bigint;
    choreId: [] | [bigint];
    transactionId: bigint;
}): {
    transactionType: TransactionType;
    note?: string;
    amountCents: bigint;
    childId: bigint;
    timestamp: bigint;
    choreId?: bigint;
    transactionId: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        note: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.note)),
        amountCents: value.amountCents,
        childId: value.childId,
        timestamp: value.timestamp,
        choreId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.choreId)),
        transactionId: value.transactionId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    rewardCents: bigint;
    frequency: _Frequency;
    assignedChildIds: Array<bigint>;
    choreId: bigint;
}): {
    name: string;
    rewardCents: bigint;
    frequency: Frequency;
    assignedChildIds: Array<bigint>;
    choreId: bigint;
} {
    return {
        name: value.name,
        rewardCents: value.rewardCents,
        frequency: from_candid_Frequency_n21(_uploadFile, _downloadFile, value.frequency),
        assignedChildIds: value.assignedChildIds,
        choreId: value.choreId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    completionId: bigint;
    childId: bigint;
    timestamp: bigint;
    choreId: bigint;
}): {
    status: Variant_pending_approved_rejected;
    completionId: bigint;
    childId: bigint;
    timestamp: bigint;
    choreId: bigint;
} {
    return {
        status: from_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        completionId: value.completionId,
        childId: value.childId,
        timestamp: value.timestamp,
        choreId: value.choreId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    linkedChildId: [] | [bigint];
}): {
    name: string;
    role: string;
    linkedChildId?: bigint;
} {
    return {
        name: value.name,
        role: value.role,
        linkedChildId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.linkedChildId))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deduction: null;
} | {
    choreComplete: null;
}): TransactionType {
    return "deduction" in value ? TransactionType.deduction : "choreComplete" in value ? TransactionType.choreComplete : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlimitedDaily: null;
} | {
    oncePerWeek: null;
} | {
    oncePerDay: null;
}): Frequency {
    return "unlimitedDaily" in value ? Frequency.unlimitedDaily : "oncePerWeek" in value ? Frequency.oncePerWeek : "oncePerDay" in value ? Frequency.oncePerDay : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chore>): Array<Chore> {
    return value.map((x)=>from_candid_Chore_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChoreCompletion>): Array<ChoreCompletion> {
    return value.map((x)=>from_candid_ChoreCompletion_n25(_uploadFile, _downloadFile, x));
}
function to_candid_Frequency_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    linkedChildId?: bigint;
}): {
    name: string;
    role: string;
    linkedChildId: [] | [bigint];
} {
    return {
        name: value.name,
        role: value.role,
        linkedChildId: value.linkedChildId ? candid_some(value.linkedChildId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): {
    unlimitedDaily: null;
} | {
    oncePerWeek: null;
} | {
    oncePerDay: null;
} {
    return value == Frequency.unlimitedDaily ? {
        unlimitedDaily: null
    } : value == Frequency.oncePerWeek ? {
        oncePerWeek: null
    } : value == Frequency.oncePerDay ? {
        oncePerDay: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
